name: Annotate pull requests with regression summaries

on:
  workflow_run:
    workflows:
      - Continuous Integration
      - Testing
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
      # based on https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
      - name: 'Download regression_summary artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "regression_summary"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: matchArtifact.id,
              archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/regression_summary.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip regression_summary.zip

      - name: 'Get pull request number'
        id: pr_number
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let fs = require('fs');
            let readline = require('readline');
            let issue_number = 0;
            const fileStream = fs.createReadStream('summary.txt');
            const rl = readline.createInterface({
              input: fileStream,
              crlfDelay: Infinity
            });
            rl.on('line', (line) => {
              console.log('First line:', line);
              issue_number = Number(line);
              rl.close();
              fileStream.close();
              return issue_number;
            });

      - name: Write Results to PR
        uses: thollander/actions-comment-pull-request@v2
        env:
          PR_NUMBER: ${{ steps.pr_number.outputs.result }}
        with:
          filePath: summary.txt
          pr_number: ${{ env.PR_NUMBER }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

